### ISSUE TITLE
headset only has 3Dof tracking

### ISSUE THREAD

**Issue by benjamincheng10** [Gistix/portal2vr#51] opened 2023-09-19 08:55 UTC
When playing on my headset, i only have 3Dof tracking while the Portal gun has full 6Dof. Really wierd

**Comment by HexHyte** [comment] 2023-09-19 09:24
Duplicate of https://github.com/Gistix/portal2vr/issues/31

set 6DOF=true
in
steamapps/common/Portal 2/VR/config.txt

**Comment by J-Emil-P** [comment] 2023-09-21 05:52
@benjamincheng10 remember to close the issue if it was fixed

**Closed** 2023-09-21 22:40 UTC

**Comment by jurassicjordan** [comment] 2024-06-11 23:02
Why is that config disabled by default?
